version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: pokemon_db
    restart: always
    environment:
      POSTGRES_USER: champions_user
      POSTGRES_PASSWORD: champions_password
      POSTGRES_DB: pokemon_champions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: