spring.application.name=backend

# Configuración de la Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_champions
spring.datasource.username=champions_user
spring.datasource.password=champions_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará las tablas automáticamente si no usas Flyway todavía
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
